version: '2'
services:
  shield:
    image: shield
    build:
      context: ./daemon
    depends_on:
      - pg-ssl
    command: ["./wait-for-it.sh", "pg-ssl:5432", "-t", "30", "--", "/shield-server-linux-amd64/start-shield.sh"]
  shield-agent:
    build:
      context: .
      dockerfile: ./agent/Dockerfile
  web:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./ssl.key:/etc/nginx/ssl.key:ro
    - ./ssl.crt:/etc/nginx/ssl.crt:ro
    ports:
    - "443:443"
    - "80:80"
    depends_on:
      - shield
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shield
  pg-ssl:
    build:
      context: ./postgres-ssl
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shield
